### ISSUE TITLE
Filtering by framework (React, Vue, etc)

### ISSUE THREAD

**Issue by trusktr** [inbn/component-gallery#14]
Hello! First of all, component.gallery is awesome! 

On either of the main pages (https://component.gallery/components and https://component.gallery/design-systems) there are neat labels.

- It would be nice to filter by labels (I'm sure you thought of that!)
- and it would be nice to have labels for the design systems, and also for the underlying component systems used
  - "Components systems" labels would be for example `React`, `Vue`, `Lightning`, or even more generic labels like `Web Components` which would be on anything that also has `Stencil` or `Lightning`, etc.
  
I'd like to add my system here too. When I get to it, I'll try to see if I can add some of these features too. :D

**Comment by inbn** [comment]
Hi there! 👋  

Thanks for your interest in the project! This is something I have been planning for a while and it's near the top of the feature list. I just need to set aside some time to work on it.

My first priority is setting up an example airtable with the correct schema, so other developers can contribute to the project, without me needing to provide access to the original airtable (which I'm not currently planning on doing). There's another open issue for that which I hope to get that done this weekend.

Also, in the meantime, if you have any design systems you think would be a good fit for the project, feel free to contact me on Twitter.

**Comment by trusktr** [comment]
> My first priority is setting up an example airtable with the correct schema, so other developers can contribute to the project, without me needing to provide access to the original airtable (which I'm not currently planning on doing). 

Yeah, that'd be great. Just read the other issue.

I'll share the site with a few other people who are making design systems or components, and they can get in touch. :)

**Comment by inbn** [comment]
Filtering by Features and Tech added in #16
