### ISSUE TITLE
Unmaintained design system

### ISSUE THREAD

**Issue by aardrian** [inbn/component-gallery#40]
Near as I can tell, [A11y Style Guide](https://a11y-style-guide.com/style-guide/) is no longer being maintained.

- The [most recent update](https://github.com/cehfisher/a11y-style-guide) was a year ago and only to remove the name of someone who is no longer active with it.
- It has [open issues back to 2017](https://github.com/cehfisher/a11y-style-guide/issues) including bugs in the patterns.
- Project maintainer said two weeks ago she has "[set the repo aside](https://web-a11y.slack.com/archives/C042TSFGN/p1665512990748099?thread_ts=1665413829.809119&cid=C042TSFGN)" and has "kept the repo in place for historical purposes."

I do not know Gatsby and cannot figure out where the data is stored or I would file the PR with this note.

**Comment by inbn** [comment]
Hi @aardrian — thanks for filing an issue. The data is coming from a private Airtable database so it's only me who can make those updates right now. 

As a rule, I don't remove design systems that are no longer maintained — they might still be useful to some people. However, I think that adding an obvious 'unmaintained' flag to these design systems could be handy for warning people in advance that the content there may be out-of-date.

**Comment by aardrian** [comment]
I should have figured the data was not in a buried JSON file.

I like the idea of an "unmaintained" flag. So I guess adjust my issue to be a request to mark entries as unmaintained?

**Comment by aardrian** [comment]
I think that flag absolutely works for now. Given your rule above, this satisfies my request.

Thank you!
