### ISSUE TITLE
Broken links on Button

### ISSUE THREAD

**Issue by amyrlam** [inbn/component-gallery#65]
https://component.gallery/components/button/ - Wanda - Icon Button. Current link is dead, should be https://wonderflow-bv.github.io/wanda/?path=/story/actions-icon-button--default

Also, happy to help with the dead links if you are interested!

**Comment by inbn** [comment]
I have updated that link to point to the [Get started docs page for Icon button](https://design.wonderflow.ai/get-started/components/actions/icon-button). Unfortunately, I'm the only one who can update component links right now but please continue to point out any broken links you find. Thanks!

**Comment by amyrlam** [comment]
cool, thanks!
