### ISSUE TITLE
Page design-systems/ causes high CPU load

### ISSUE THREAD

**Issue by rebootl** [inbn/component-gallery#68]
Hello, I love the collection.

But somehow the page https://component.gallery/design-systems/ causes a high CPU load on my system.

It happens in firefox and chromium similarly.
I'm using arch Linux with wayland but I don't think this is related.

I used the firefox profiler but I'm honestly not sure on how to read this.

![Screenshot From 2024-11-22 14-16-12](https://github.com/user-attachments/assets/fbe58611-0b49-448c-9399-b44a764e4649)

One thing I can see there is that the memory usage keeps going up. Which seems like it shouldn't happen.
Also when I disable Javascript the problem does not happen at all.

Best

**Comment by inbn** [comment]
Hi, thanks for reporting the issue. 

I know this page has many thousands of DOM elements and the site's using react, which would together contribute to high resource usage but that screenshot definitely seems abnormal. I'm seeing 100% CPU usage but normal-looking memory usage on chrome on my Mac. I'll have a look into what could be causing this – I suspect a bunch of unnecessary re-renders.

P.S. I'm currently working on v2 of the site in Astro, which won't use react for rendering these components.

**Comment by inbn** [comment]
@rebootl I think I've found the problem but let me know if you're still seeing issues.

**Comment by rebootl** [comment]
I can confirm it's fixed :+1: thank you
